services:
  mongodb:
    image: mongo:8
    container_name: ecom-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecom
    volumes:
      - ecom-mongodb-data:/data/db

volumes:
  ecom-mongodb-data:
