using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
[ApiController,Authorize(Roles="ADMIN"),Route("api/admin/products")]
public sealed class AdminProductsController(EComDbContext db):ControllerBase
{
 [HttpPost] public async Task<IActionResult>Create(ProductRequest r){if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Sku)||r.Price<0||r.StockQuantity<0)return BadRequest(new{message="Valid name, SKU, price and stock are required."});if(!await db.Categories.AnyAsync(x=>x.Id==r.CategoryId&&x.IsActive))return BadRequest(new{message="Invalid category."});if(await db.Products.AnyAsync(x=>x.Sku==r.Sku.Trim()))return Conflict(new{message="SKU already exists."});var p=new Product{CategoryId=r.CategoryId,Name=r.Name.Trim(),Sku=r.Sku.Trim(),Description=r.Description?.Trim(),Price=r.Price,CompareAtPrice=r.CompareAtPrice,StockQuantity=r.StockQuantity,IsActive=r.IsActive};db.Products.Add(p);await db.SaveChangesAsync();await ReplaceImages(p,r.ImageUrls);await db.SaveChangesAsync();return Created($"api/products/{p.Id}",new{p.Id});}
 [HttpPut("{id:long}")]public async Task<IActionResult>Update(long id,ProductRequest r){var p=await db.Products.Include(x=>x.Images).SingleOrDefaultAsync(x=>x.Id==id);if(p is null)return NotFound();if(!await db.Categories.AnyAsync(x=>x.Id==r.CategoryId&&x.IsActive))return BadRequest(new{message="Invalid category."});p.Name=r.Name.Trim();p.CategoryId=r.CategoryId;p.Description=r.Description?.Trim();p.Price=r.Price;p.CompareAtPrice=r.CompareAtPrice;p.StockQuantity=Math.Max(0,r.StockQuantity);p.IsActive=r.IsActive;p.UpdatedAt=DateTimeOffset.UtcNow;await ReplaceImages(p,r.ImageUrls);await db.SaveChangesAsync();return Ok();}
 [HttpDelete("{id:long}")]public async Task<IActionResult>Delete(long id){var p=await db.Products.FindAsync(id);if(p is null)return NotFound();p.IsDeleted=true;p.IsActive=false;p.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return NoContent();}
 async Task ReplaceImages(Product p,IEnumerable<string>? urls){db.ProductImages.RemoveRange(p.Images);var clean=(urls??[]).Where(x=>Uri.TryCreate(x,UriKind.Absolute,out _)).Distinct().Take(8).ToList();for(var i=0;i<clean.Count;i++)db.ProductImages.Add(new ProductImage{ProductId=p.Id,Url=clean[i],DisplayOrder=i,IsPrimary=i==0});await Task.CompletedTask;}
}
public sealed record ProductRequest(long CategoryId,string Name,string Sku,string? Description,decimal Price,decimal? CompareAtPrice,int StockQuantity,bool IsActive=true,IEnumerable<string>? ImageUrls=null);
