using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
[ApiController,Authorize,Route("api/cart")]
public sealed class CartController(EComDbContext db):ControllerBase
{
 long UserId=>long.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [HttpGet]public async Task<IActionResult>Get(){var cart=await db.Carts.Include(c=>c.Items).ThenInclude(i=>i.Product).ThenInclude(p=>p.Images).SingleOrDefaultAsync(c=>c.UserId==UserId);return Ok(cart?.Items.Select(i=>new{i.Id,i.ProductId,i.Quantity,i.UnitPrice,i.Product.Name,Image=i.Product.Images.OrderBy(x=>x.DisplayOrder).Select(x=>x.Url).FirstOrDefault(),LineTotal=i.UnitPrice*i.Quantity})??[]);}
 [HttpPost("items")]public async Task<IActionResult>Add(AddCartItemRequest r){if(r.Quantity<1)return BadRequest();var p=await db.Products.SingleOrDefaultAsync(x=>x.Id==r.ProductId&&x.IsActive&&!x.IsDeleted);if(p is null)return NotFound();if(p.StockQuantity<r.Quantity)return BadRequest(new{message="Insufficient stock."});var c=await db.Carts.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.UserId==UserId);if(c is null){c=new Cart{UserId=UserId};db.Carts.Add(c);}var item=c.Items.SingleOrDefault(x=>x.ProductId==p.Id);var old=item?.Quantity??0;if(item is null)c.Items.Add(new CartItem{ProductId=p.Id,Quantity=r.Quantity,UnitPrice=p.Price});else{item.Quantity+=r.Quantity;if(item.Quantity>p.StockQuantity)return BadRequest(new{message="Insufficient stock."});item.UnitPrice=p.Price;}c.UpdatedAt=DateTimeOffset.UtcNow;db.AuditLogs.Add(new AuditLog{UserId=UserId,Action="CART_ADD",EntityType="PRODUCT",EntityId=p.Id.ToString(),OldValue=old.ToString(),NewValue=(old+r.Quantity).ToString()});await db.SaveChangesAsync();return Ok();}
 [HttpPatch("items/{id:long}")]public async Task<IActionResult>Update(long id,UpdateCartItemRequest r){var item=await db.CartItems.Include(x=>x.Cart).Include(x=>x.Product).SingleOrDefaultAsync(x=>x.Id==id&&x.Cart.UserId==UserId);if(item is null)return NotFound();if(r.Quantity<1){db.CartItems.Remove(item);await db.SaveChangesAsync();return NoContent();}if(r.Quantity>item.Product.StockQuantity)return BadRequest(new{message="Insufficient stock."});var old=item.Quantity;item.Quantity=r.Quantity;item.UnitPrice=item.Product.Price;item.Cart.UpdatedAt=DateTimeOffset.UtcNow;db.AuditLogs.Add(new AuditLog{UserId=UserId,Action="CART_UPDATE",EntityType="PRODUCT",EntityId=item.ProductId.ToString(),OldValue=old.ToString(),NewValue=r.Quantity.ToString()});await db.SaveChangesAsync();return Ok();}
 [HttpDelete("items/{id:long}")]public async Task<IActionResult>Remove(long id){var item=await db.CartItems.Include(x=>x.Cart).SingleOrDefaultAsync(x=>x.Id==id&&x.Cart.UserId==UserId);if(item is null)return NotFound();db.AuditLogs.Add(new AuditLog{UserId=UserId,Action="CART_REMOVE",EntityType="PRODUCT",EntityId=item.ProductId.ToString(),OldValue=item.Quantity.ToString(),NewValue="0"});db.CartItems.Remove(item);await db.SaveChangesAsync();return NoContent();}
}
public sealed record AddCartItemRequest(long ProductId,int Quantity);public sealed record UpdateCartItemRequest(int Quantity);
