using System.Security.Claims; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
[ApiController,Authorize,Route("api/orders")]
public sealed class OrdersController(EComDbContext db):ControllerBase
{
 long UserId=>long.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [HttpPost]
 public async Task<IActionResult> Create(CreateOrderRequest r){if(string.IsNullOrWhiteSpace(r.FullName)||string.IsNullOrWhiteSpace(r.Phone)||string.IsNullOrWhiteSpace(r.Line1)||string.IsNullOrWhiteSpace(r.City)||string.IsNullOrWhiteSpace(r.State)||string.IsNullOrWhiteSpace(r.PostalCode))return BadRequest(new{message="Complete delivery address is required."});var cart=await db.Carts.Include(c=>c.Items).ThenInclude(i=>i.Product).SingleOrDefaultAsync(c=>c.UserId==UserId);if(cart is null||cart.Items.Count==0)return BadRequest(new{message="Cart is empty."});foreach(var i in cart.Items)if(i.Product.StockQuantity<i.Quantity||!i.Product.IsActive||i.Product.IsDeleted)return BadRequest(new{message=$"Product unavailable: {i.Product.Name}"});var address=new Address{UserId=UserId,FullName=r.FullName.Trim(),Phone=r.Phone.Trim(),Line1=r.Line1.Trim(),Line2=r.Line2?.Trim(),City=r.City.Trim(),State=r.State.Trim(),PostalCode=r.PostalCode.Trim()};var now=DateTimeOffset.UtcNow;var order=new Order{OrderNumber=$"ORD-{now:yyyyMMddHHmmss}-{Random.Shared.Next(100,999)}",UserId=UserId,ShippingAddress=address,Subtotal=cart.Items.Sum(i=>i.Product.Price*i.Quantity),TotalAmount=cart.Items.Sum(i=>i.Product.Price*i.Quantity),PaymentStatus="PENDING",OrderStatus="PENDING_PAYMENT",PaymentMethod="PAYTM",EstimatedDeliveryFrom=now.AddDays(7),EstimatedDeliveryTo=now.AddDays(15)};foreach(var i in cart.Items){i.Product.StockQuantity-=i.Quantity;order.Items.Add(new OrderItem{ProductId=i.ProductId,ProductName=i.Product.Name,ProductSku=i.Product.Sku,Quantity=i.Quantity,UnitPrice=i.Product.Price,TotalPrice=i.Product.Price*i.Quantity});}await using var tx=await db.Database.BeginTransactionAsync();db.Orders.Add(order);await db.SaveChangesAsync();db.Payments.Add(new Payment{OrderId=order.Id,Amount=order.TotalAmount,Status="INITIATED",PaymentGateway="PAYTM"});db.CartItems.RemoveRange(cart.Items);db.AuditLogs.Add(new AuditLog{UserId=UserId,Action="ORDER_CREATED",EntityType="ORDER",EntityId=order.OrderNumber,NewValue=$"Total={order.TotalAmount};Items={order.Items.Count}"});await db.SaveChangesAsync();await tx.CommitAsync();return Ok(new{order.Id,order.OrderNumber,order.TotalAmount,order.EstimatedDeliveryFrom,order.EstimatedDeliveryTo,paymentStatus=order.PaymentStatus});}
 [HttpGet] public async Task<IActionResult> List()=>Ok(await db.Orders.AsNoTracking().Where(o=>o.UserId==UserId).OrderByDescending(o=>o.CreatedAt).Select(o=>new{o.Id,o.OrderNumber,o.TotalAmount,o.PaymentStatus,o.OrderStatus,o.PaymentMethod,o.CreatedAt,o.EstimatedDeliveryFrom,o.EstimatedDeliveryTo,itemCount=o.Items.Count}).ToListAsync());
 [HttpGet("{id:long}")] public async Task<IActionResult> Get(long id){var o=await db.Orders.AsNoTracking().Include(x=>x.Items).Include(x=>x.ShippingAddress).SingleOrDefaultAsync(x=>x.Id==id&&x.UserId==UserId);return o is null?NotFound():Ok(o);}
}
public sealed record CreateOrderRequest(string FullName,string Phone,string Line1,string? Line2,string City,string State,string PostalCode);
