using System.Security.Claims; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
[ApiController,Authorize,Route("api/orders")]
public sealed class OrdersController(EComDbContext db):ControllerBase
{
 long UserId=>long.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [HttpPost] public async Task<IActionResult> Create(CreateOrderRequest r){var cart=await db.Carts.Include(c=>c.Items).ThenInclude(i=>i.Product).SingleOrDefaultAsync(c=>c.UserId==UserId);if(cart is null||cart.Items.Count==0)return BadRequest(new{message="Cart is empty."});if(string.IsNullOrWhiteSpace(r.FullName)||string.IsNullOrWhiteSpace(r.Phone)||string.IsNullOrWhiteSpace(r.Line1)||string.IsNullOrWhiteSpace(r.City)||string.IsNullOrWhiteSpace(r.State)||string.IsNullOrWhiteSpace(r.PostalCode))return BadRequest(new{message="Complete delivery address is required."});foreach(var i in cart.Items)if(i.Product.StockQuantity<i.Quantity||!i.Product.IsActive||i.Product.IsDeleted)return BadRequest(new{message=$"Product unavailable: {i.Product.Name}"});var subtotal=cart.Items.Sum(i=>i.Product.Price*i.Quantity);var now=DateTimeOffset.UtcNow;var order=new Order{OrderNumber=$"ORD-{now:yyyyMMddHHmmss}-{Random.Shared.Next(100,999)}",UserId=UserId,Subtotal=subtotal,TotalAmount=subtotal,PaymentStatus="PENDING",OrderStatus="PENDING_PAYMENT",EstimatedDeliveryFrom=now.AddDays(7),EstimatedDeliveryTo=now.AddDays(15),ShippingAddress=new Address{UserId=UserId,FullName=r.FullName,Phone=r.Phone,Line1=r.Line1,Line2=r.Line2,City=r.City,State=r.State,PostalCode=r.PostalCode}};foreach(var i in cart.Items){i.Product.StockQuantity-=i.Quantity;order.Items.Add(new OrderItem{ProductId=i.ProductId,ProductName=i.Product.Name,ProductSku=i.Product.Sku,Quantity=i.Quantity,UnitPrice=i.Product.Price,TotalPrice=i.Product.Price*i.Quantity});}db.Orders.Add(order);db.Payments.Add(new Payment{Order=order,Amount=subtotal,Status="INITIATED"});db.CartItems.RemoveRange(cart.Items);db.AuditLogs.Add(new AuditLog{UserId=UserId,Action="ORDER_CREATED",EntityType="ORDER",EntityId=order.OrderNumber,NewValue=$"Total={subtotal}"});await db.SaveChangesAsync();return Ok(new{order.Id,order.OrderNumber,order.TotalAmount,order.EstimatedDeliveryFrom,order.EstimatedDeliveryTo,paymentStatus=order.PaymentStatus});}
 [HttpGet] public async Task<IActionResult> List(){return Ok(await db.Orders.AsNoTracking().Where(o=>o.UserId==UserId).OrderByDescending(o=>o.CreatedAt).Select(o=>new{o.Id,o.OrderNumber,o.TotalAmount,o.PaymentStatus,o.OrderStatus,o.CreatedAt,o.EstimatedDeliveryFrom,o.EstimatedDeliveryTo}).ToListAsync());}
 [HttpGet("{id:long}")] public async Task<IActionResult> Get(long id){var o=await db.Orders.AsNoTracking().Include(x=>x.Items).Include(x=>x.ShippingAddress).SingleOrDefaultAsync(x=>x.Id==id&&x.UserId==UserId);return o is null?NotFound():Ok(o);}
}
public sealed record CreateOrderRequest(string FullName,string Phone,string Line1,string? Line2,string City,string State,string PostalCode);
